language: cpp

branches:
  only:
    - master
    - /^test.*$/

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8

cache:
  directories:
    - $HOME/.dotnet
    - $HOME/.nuget

addons:
  artifacts:
    s3_region: "us-west-2"
    paths: $(ls powershell*{deb,pkg} | tr "\n" ":")

git:
  submodules: false

install:
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - git submodule update --init
  - (cd tools && ./download.sh)

script: ./tools/travis.sh
