version: 0.4.0.{build}

nuget:
  project_feed: true

environment:
  priv_key:
    secure: <encryped-value>

notifications:
  - provider: Slack
    incoming_webhook:
      secure: bwwXBTeJBtRFea6FSQKzVENLwL0AOeusUSUFIh/TeHA4y0UFk7bC9+OcxgZW+YfIC0VZyTpZClJHlPFFHSgiQs4g9om17RxzJEeq4EjsW5g=

install:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - git submodule update --init -- src/Modules/Pester
  - ps: Import-Module .\build.psm1; Start-PSBootstrap

build_script:
  - ps: |
      $ErrorActionPreference = 'Stop'
      Start-PSBuild -Publish
      Start-PSBuild -FullCLR

test_script:
  - ps: |
      Write-Host -Foreground Green "== SKIP TESTS =="


on_finish: 
  - ps: |
      $ErrorActionPreference = 'Stop'
      try {
        # Build packages
        $packages = Start-PSPackage
        
        # Creating project artifact
        $name = git describe
        $zipFilePath = Join-Path $pwd "$name.zip"
        $zipFileFullPath = Join-Path $pwd "$name.FullCLR.zip"
        Add-Type -assemblyname System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory($env:CoreOutput, $zipFilePath)
        [System.IO.Compression.ZipFile]::CreateFromDirectory($env:FullOutput, $zipFileFullPath)
        
        $artifacts = New-Object System.Collections.ArrayList
        foreach ($package in $packages) {
        $artifacts.Add($package)
        }
        
        $artifacts.Add($zipFilePath)
        $artifacts.Add($zipFileFullPath)

        Publish-NuGetFeed -OutputPath .\nuget-artifacts -VersionSuffix "b$($env:APPVEYOR_BUILD_NUMBER)"

        $artifacts += (ls .\nuget-artifacts | % {$_.FullName})

        $artifacts | % { 
            Write-Host "Pushing $_ as Appveyor artifact"
            Push-AppveyorArtifact $_
          }
      } catch {
        Write-Host -Foreground Red $_
      }
